### ISSUE TITLE
False ban - Attempted to spawn a vehicle

### ISSUE THREAD

**Issue by Toonnio** [WaveShieldDev/WaveShield#1]
False ban for spawn vehicle

![image](https://github.com/WaveShieldDev/WaveShield/assets/74127071/1bde7965-8ef9-488e-a908-833f0f786758)
![image](https://github.com/WaveShieldDev/WaveShield/assets/74127071/a76c422a-1290-4b04-aec5-702f22d0ea95)
![image](https://github.com/WaveShieldDev/WaveShield/assets/74127071/96d0c700-2e76-40ce-ae95-82a2002b9033)

**Comment by Jqstln** [comment]
Could you show the "Vehicles" tab from the WaveShield Panel?

**Comment by Toonnio** [comment]
![image](https://github.com/WaveShieldDev/WaveShield/assets/74127071/3f9de3bc-cb03-4d97-976a-119c425602a8)


Without that, I'm not worried, I hadn't paid special attention to the "beta"

**Comment by AYZNN** [comment]
Hi, do you have any idea on how it's happening? How can we reproduce it?

**Comment by Toonnio** [comment]
clueless happens randomly

**Comment by unlcky485** [comment]
bro iv been banned for no reason

**Comment by Jqstln** [comment]
Is the car blacklisted by any chance?

**Comment by Toonnio** [comment]
Non pas bl

**Comment by victorenstudios** [comment]
It usually happens when a player is driving too fast

**Comment by AYZNN** [comment]
Fixed in 4.1.42
