### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by imBoldPilot** [WaveShieldDev/WaveShield#11]
**Description**

Anti Add-on Files 
**Benefits**

There is so many aim bot add on files are working try to detect them

**Additional Context**

i can send the files that works while ac is working so you can have a look

**Comment by AYZNN** [comment]
Hi, wdym add on files? Yes, feel free to send them!

**Comment by DZaleks** [comment]
There are AI files that adapt the controller-auto-aim to keyboard/mouse. I can send them when I'm at home if needed
