### ISSUE TITLE
Explosion Detection

### ISSUE THREAD

**Issue by Amir-Khedi** [WaveShieldDev/WaveShield#12]
"Cancel All Explosions" doesn't work like before anymore.
The effects of explosions can only be seen by the one who created them but it still kills the played who is in range of that explosion (They can't see it but they die).
You can go to Sandy Shores to explode gas canisters to check. Once you shoot one it starts exploding repeatedly until you get further from it (That's not the problem). If you ask someone else to stay in the range of that explosion, they die but only you can see the effect (They'll die until you don't see the explosion).

**Comment by AYZNN** [comment]
Damages removed in the next update.
