### ISSUE TITLE
Anti Spoofing/Aimbot

### ISSUE THREAD

**Issue by Sickoskill074** [WaveShieldDev/WaveShield#16]
Blocking Aimbot and see if a player has a new steam/ discord or rockstar and get banned

**Comment by Sickoskill074** [comment]
Maybe put put a file on the PC which cant be deleated where waveshield Sees that the Player got banned. Of the Player has this file he wont get unbanned even with New hwid

**Comment by 0x17Bb1** [comment]
you know that the filse stuff is not possible since it could be everything so fivem blocks it?

> Maybe put put a file on the PC which cant be deleated where waveshield Sees that the Player got banned. Of the Player has this file he wont get unbanned even with New hwid
