### ISSUE TITLE
[BUG] DRC Drug System Error

### ISSUE THREAD

**Issue by patriotgaming** [WaveShieldDev/WaveShield#3]
**Describe the Bug**

When trying to process coke_raw to coke_pure at the coke lab 

**Steps to Reproduce**

1. Turn on electricity in coke lab
2. go to any table in middle 
3. Try to process the coke_raw to coke_pure
4. See error in console

**Expected Behavior**

to not throw the error in console

**Actual Behavior**

no items given or taken, error thrown in console

**Screenshots**
![image](https://github.com/WaveShieldDev/WaveShield/assets/22457902/fe69ede2-83a0-4e8e-bf44-07bb4dd68513)

!! Ensure that there are no IP addresses or any private information in the screenshots. !!
!! Ensure that there are no IP addresses or any private information in the screenshots. !!
!! Ensure that there are no IP addresses or any private information in the screenshots. !!
!! Ensure that there are no IP addresses or any private informatio
n in the screenshots. !!

**Additional Context**
[drc_drugs.zip](https://github.com/WaveShieldDev/WaveShield/files/12289792/drc_drugs.zip)

**Comment by AYZNN** [comment]
Hi, I don't think this error is related to WaveShield, have you tried without WaveShield?

**Comment by patriotgaming** [comment]
yes i did, its when i removed waveshield it worked. let me try a fresh install of script
