### ISSUE TITLE
[BUG] esx wheel stancer error code

### ISSUE THREAD

**Issue by patriotgaming** [WaveShieldDev/WaveShield#5]
**Describe the Bug**

Menu completely stopped working due to anticheat (according to developer)

**Steps to Reproduce**

1. Does not work at all just throws this error

**Expected Behavior**

to workd

**Actual Behavior**

did not work

**Screenshots**

!! Ensure that there are no IP addresses or any private information in the screenshots. !!
!! Ensure that there are no IP addresses or any private information in the screenshots. !!
!! Ensure that there are no IP addresses or any private information in the screenshots. !!
!! Ensure that there are no IP addresses or any private information in the screenshots. !!

**Additional Context**

![](https://cdn.discordapp.com/attachments/1138864626516377620/1138864881261617202/image.png)

**Comment by AYZNN** [comment]
Hi, i'm not sure thats from WaveShield, can you drop the script? have you tried without WaveShield?

**Comment by patriotgaming** [comment]
you are correct my apologies
